import { StyleSheet } from "react-native";

export default StyleSheet.create({
  warning: {
    backgroundColor: "#ff8800",
  },
  danger: {
    backgroundColor: "#ff3547",
  },
  success: {
    backgroundColor: "#01c850",
  },
  timeTaken: {
    marginLeft: 15,
    backgroundColor: "#fff",
    padding: 10,
  },
  bottomAlertButton: {
    padding: 12,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "#fff",
  },
  bottomAlertText: {
    color: "#fff",
    // fontFamily: "Roboto-Regular",
    fontWeight: "bold",
    fontSize: 17,
  },
  messageHeadText: {
    // fontFamily: "Roboto-Bold",
    fontSize: 17,
    marginRight: 30,
    marginLeft: 20,
    marginTop: 5,
  },
  messageHead: {
    margin: 10,
    borderColor: "#101010",
    borderWidth: 2,
    borderRadius: 20,
    backgroundColor: "#f0f0f0",
  },
  copyMessage: {
    display: "flex",
    margin: 5,
    padding: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#e0e0e0",
    borderRadius: 30,
  },
  copyIcon: {
    marginTop: 7,
    alignItems: "flex-end",
    marginRight: 30,
  },
  qrTextBox: {
    padding: 5,
    marginLeft: 20,
    marginRight: 20,
    display: "flex",
    flexDirection: "row",
    flex: 1,
  },
  qrText: {
    backgroundColor: "#f0f0f0",
    marginLeft: 10,
    marginRight: 10,
    flexWrap: "wrap",
    flex: 1,
    justifyContent: "flex-end",
  },
  previewTitle: {
    // fontFamily: "Roboto-Regular",
    fontWeight: "bold",
    margin: 5,
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  previewSection: {
    height: 540,
    flex: 1,
    borderWidth: 1,
    borderColor: "blue",
    borderRadius: 40,
    marginLeft: "7%",
    width: "86%",
    marginRight: "7%",
  },
  detailsLoader: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  bold: {
    fontFamily: "Roboto-Bold",
  },
  qrDetailsDate: {
    padding: 20,
    paddingRight: 80,
    paddingTop: 20,
    marginTop: 20,
    // backgroundColor: 'red',
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  qrDetailsContainer: {
    borderWidth: 1,
    borderRadius: 40,
    margin: 10,
    paddingBottom: 15,
  },
  qrDetailsPara: {
    paddingLeft: 15,
    marginRight: 8,
    paddingTop: 8,
  },
  qrTitle: {
    marginLeft: 15,
    fontFamily: "Roboto-Bold",
  },
  qrDetailsDateText: {
    color: "#333333",
    // fontFamily: "Roboto-Regular",
    fontSize: 17,
  },
  qrShareLinkHolder: {
    flex: 1,
    display: "flex",
    flexDirection: "row",
    marginLeft: 5,
  },
  qrLinkDetails: {
    backgroundColor: "#fff",
    marginLeft: 15,
    marginRight: 15,
    borderRadius: 40,
  },
  qrImageHolder: {
    marginTop: -60,
  },
  buttonLink: {
    marginTop: 15,
    display: "flex",
    flexDirection: "row",
    paddingLeft: 10,
  },
  shareLink: {
    marginLeft: 30,
  },
  qrUrlHolder: {
    borderWidth: 1,
    borderColor: "#E8E8E8",
    marginLeft: 10,
    marginRight: 10,
    padding: 10,
    display: "flex",
    flexDirection: "row",
    marginBottom: 15,
  },
  urlHead: {
    color: "#333333",
    // fontFamily: "Roboto-Regular",
    fontSize: 17,
    marginBottom: 3,
  },
  url: {
    color: "#333333",
    fontSize: 17,
  },
  urlHolder: {
    flex: 2,
  },
  shareIcon: {
    justifyContent: "center",
    alignItems: "flex-end",
    marginRight: 3,
  },
  qrDetails: {
    backgroundColor: "#fff",
    borderRadius: 40,
    // padding: 20,
    marginTop: 10,
    margin: 15,
    paddingBottom: 15,
  },
  qrDetailsHeadText: {
    fontSize: 17,
    borderRadius: 40,
    borderBottomWidth: 1,
    // fontFamily: "Roboto-Bold",
    textAlign: "center",
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 15,
    paddingBottom: 15,
    borderColor: "#333333",
  },
  qrDetailsList: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    padding: 10,
  },
  qrDetailsListIcon: {
    width: 20,
  },
  openWithHeadText: {
    fontSize: 17,
    borderBottomWidth: 1,
    // fontFamily: "Roboto-Regular",
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 15,
    paddingBottom: 15,
    borderColor: "#333333",
  },
  qrRedirectContainer: {
    flexDirection: "row",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  qrApps: {
    flex: 1,
  },
  urlRedirect: {
    display: "flex",
    flexDirection: "row",
  },
  bottomAlertButton: {
    padding: 12,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "#fff",
    borderRadius: 40,
  },
  bottomAlertText: {
    color: "#fff",
    // fontFamily: "Roboto-Regular",
    fontWeight: "bold",
    fontSize: 17,
  },
  linearGradient: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    flexDirection: "column",
    height: "100%",
  },
  appOpenButton: {
    backgroundColor: "#00C3E6",
    padding: 20,
  },
  appOpenButtonText: {
    textAlign: "center",
    // fontFamily: "Roboto-Bold",
    fontWeight: "bold",
    color: "#fff",
    fontSize: 16,
  },
  loadingContent: {
    display: "flex",
    justifyContent: "center",
    flex: 1,
    flexDirection: "column",
  },
});
