import { StyleSheet, Platform, Dimensions } from "react-native";
const DEVICE_WIDTH = Dimensions.get("window").width;
const DEVICE_HEIGHT = Dimensions.get("window").height;
export default StyleSheet.create({
  detailsCardHolder: {
    flex: 1,
    marginTop: 60,
    display: "flex",
  },
  detailsCard: {
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingLeft: 27,
    paddingRight: 27,
    paddingBottom: 25,
    marginBottom: 20,
    paddingTop: 20,
  },
  modalCard: {
    backgroundColor: "#fff",
    height: 700,
  },
  detailsIconCenter: {
    justifyContent: "center",
    alignItems: "center",
  },
  detailsIconHolder: {
    width: 140,
    marginTop: -60,
    backgroundColor: "#fff",
    padding: 20,
    borderWidth: 1,
    borderColor: "#DEDEDE",
    paddingTop: 30,
    paddingBottom: 20,
    borderRadius: 10,
    marginBottom: 30,
    shadowColor: "#000",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.2,
    shadowRadius: 20.16,
    elevation: 20,
  },
  detailsContent: {
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
  },

  detailsProtectionBar: {
    display: "flex",
    marginTop: 5,
    flexDirection: "row",
  },
  protectionBar: {
    flex: 1,
    marginRight: 3,
  },
  safeLink: {
    backgroundColor: "#1EA15D",
    flex: 1.5,
  },
  notSafe: {
    backgroundColor: "#FF0707",
  },
  blockChainVerified: {
    backgroundColor: "#00CCFF",
    flex: 3,
  },
  protectionBarFirst: {
    // width:'60%',
    height: 3,
    flex: 2.5,
  },
  protectionBarSecond: {
    height: 3,
    backgroundColor: "#FE9B1E",
  },
  protectionBarThird: {
    height: 3,
  },
  protectionBarFourth: {
    height: 3,
  },

  feedbackIcons: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  feedBackIconClick: {
    margin: 10,
  },

  //   phone Number
  cardHeadText: {
    color: "#000000",
    alignSelf: "center",
    alignContent: "center",
    fontFamily: "Roboto",
    fontWeight: "bold",
    fontSize: 16,
    marginBottom: 14,
  },
  cardTextMain: {
    color: "#9FA5AA",
    fontFamily: "Roboto-Regular",
    fontSize: 12,
    marginBottom: 10,
  },
  buttonHolder: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  detailsIndicatorHashCode: {
    fontSize: 19,
    color: "#00CCFF",
    marginBottom: 5,
  },
  feedBackInfo: {
    //   marginBottom:20,
    //   paddingBottom:80
  },

  barText: {
    flex: 1,
    flexDirection: "row",
    marginBottom: 15,
  },
  barTextSafe: {
    flex: 4.5,
    color: "#00CCFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  barTextDanger: {
    flex: 1,
    color: "#FF3636",
    fontSize: 16,
    fontWeight: "bold",
  },
  barContent: {
    flex: 1,
    flexDirection: "row",
  },

  barContentBlock: {
    color: "black",
    paddingTop: 15,
    flex: 4.6,
  },
  barContentBlockDanger: {
    color: "black",
    paddingTop: 15,
    flex: 6,
  },
  barContentBlockTrust: {
    color: "black",
    paddingTop: 15,
    flex: 4.5,
  },
  barContentImageTrust: {
    flex: 4.5,
  },
  barContentImageWarning: {
    flex: 2,
  },
  barContentImageDanger: {
    flex: 1,
  },
  hashMarkContent: {
    color: "#00CCFF",
    paddingTop: 10,
    paddingLeft: 5,
    fontSize: 15,
  },
  showDataHeader: {
    color: "#1a78eb",
    fontSize: 13,
  },
  sslText: {
    fontSize: 12,
    fontFamily: "Roboto-Regular",
    color: "#3E3E3E",
    marginTop: 4,
    flex: 6,
  },
  detailsRedirectLinkHolder: {
    borderWidth: 1,
    borderColor: "#E8E8E8",
    borderRadius: 5,
    padding: 10,
    marginTop: 15,
  },
  detailsRedirectLinkHeader: {
    display: "flex",
    flexDirection: "row",
    flex: 1,
  },
  detailsRedirectLinkText: {
    // fontFamily: "Roboto-Regular",
    fontSize: 15,
    color: "#666666",
    flex: 2,
  },
  detailsShare: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    flexDirection: "row",
    // marginTop: 8,
  },
  detailsShareButtons: {
    // padding: 15,
    paddingBottom: 0,
  },
  detailsLinkText: {
    fontSize: 17,
    // fontFamily: "Roboto-Bold",
    // marginTop: 18,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    fontWeight: "bold",
    marginBottom: 10,
    marginLeft: 8,
    color: "#333333",
    textDecorationLine: "underline",
  },
  sslIcon: {
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    display: "flex",
    justifyContent: "flex-start",
  },
  webCard: {
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingLeft: 27,
    paddingRight: 27,
    paddingBottom: 25,
    marginBottom: 20,
    paddingTop: 20,
    height: 1000,
  },
  infoModalHead: {
    display: "flex",
    flexDirection: "row",
    marginBottom: 10,
  },
  infoModalContainer: {
    paddingLeft: 20,
    paddingRight: 20,
  },
  headTextHold: {
    marginLeft: 15,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  modalHeader: {
    fontSize: 20,
    color: "#1a78eb",
    paddingBottom: 15,
  },
  //more Info button

  appOpenButton: {
    backgroundColor: "#00C3E6",
    padding: 5,
    borderRadius: 5,
    marginTop: 10,
  },
  appOpenButtonText: {
    textAlign: "center",
    fontWeight: "bold",
    color: "#fff",
    fontSize: 16,
  },
  activityIndicatorStyle: {
    flex: 1,
    position: "absolute",
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: "auto",
    marginBottom: "auto",
    paddingTop: 20,
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: "flex-start",
  },
  imageAlign: {
    width: "100%",
    height: 100,
    aspectRatio: 1,
    alignSelf: "center",
    flex: 1,
    resizeMode: "contain",
    // padding:10,
    marginBottom: 20,
    marginTop: 20,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  imageContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  keyData: {
    borderRightWidth: 1,
    borderTopWidth: 1,
    borderColor: "#8898aa",
    flex: 1,
    paddingVertical: 20,
    paddingHorizontal: 10,
    flexDirection: "column",
    // textAlign: "center",
    justifyContent: "center",
    textAlignVertical: "center",
  },
  valueData: {
    borderTopWidth: 1,
    overflow: "hidden",
    borderColor: "#8898aa",
    flex: 1,
    flexDirection: "column",
    textAlign: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    // padding: 20,
  },
  tableHolder: {
    flex: 1,
    flexDirection: "row",
    borderColor: "#8898aa",
    // borderTopWidth: 1,

    borderLeftWidth: 1,
    borderRightWidth: 1,
  },
  outsideContainer: {
    flex: 1,
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    flex: 1,
  },
  textError: {
    color: "red",
    fontSize: 20,
    margin: 10,
    fontWeight: "bold",
    textAlign: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  privateText: {
    color: "#5e72e4",
    fontSize: 16,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 20,
    paddingBottom: 20,
    fontWeight: "bold",
    textAlign: "center",
  },
});
