require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'SEQR' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  # pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  # pod 'GoogleMLKit/BarcodeScanning'
  
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
    # 'TextDetector',
    # 'FaceDetectorMLKit',
    'BarcodeDetectorMLKit',
    # 'LabelDetectorMLKit',
  ]

  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'SEQRTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  post_install do |installer|
   # flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end

target 'SEQR-tvOS' do
  # Pods for SEQR-tvOS

  target 'SEQR-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
